/*
-- Query: SELECT * FROM mydatabase.Hotel
LIMIT 0, 1000

-- Date: 2014-11-27 16:41
*/
INSERT INTO `hotel` (`cnpj`,`ddd`,`descricao`,`link1`,`link2`,`link3`,`nome`,`pais`,`preco`,`qtdEstrelas`,`telefone`,`linkTitle`) VALUES ('744 434 0100','52','A localização, as instalações totalmente reformadas e o padrão de atendimento fazem do Acapulco uma das melhores opções de hospedagem no Cabo Marques para quem vem a negócios ou à lazer.','http://blog.malapronta.com.br/wp-content/uploads/2012/01/019.jpg','http://3.bp.blogspot.com/-kyVT3vMN1z8/TgKRwQCZIMI/AAAAAAAAB38/fllBAQ1-Nrk/s1600/hoteis-decolar-pacotes.jpg','http://conexaoal.com/wp-content/uploads/2014/04/cinco-hoteis-de-sonho-em-portugal.jpg','Banyan Tree','México','700,00','4','744 434 0101','http://www.banyantree.com/en/web/banyantree/em-mexico-cabo-marques');
INSERT INTO `hotel` (`cnpj`,`ddd`,`descricao`,`link1`,`link2`,`link3`,`nome`,`pais`,`preco`,`qtdEstrelas`,`telefone`,`linkTitle`) VALUES ('12345678','66','Aproveite as ocasiões: Lhe oferecemos nossa lendária hospitalidade Thailandesa para um novo nível, combinando vistas de tirar o folego, suítes muito luxuosas e restaurantes e bares perfeitos para comemorações. O resultado é um dos melhores hotéis de 5 estrelas do mundo lhe trazendo uma nova e inesquecível experiência a cada momento. ','http://www.lebua.com/page/-/restaurant/gallery-580x385-mezzaluna2_2.jpg/@mx_580','http://www.lebua.com/page/-/restaurant/Distil%20Ciger%20Terrace_1_resize.jpg/@mx_580','http://www.tnetnoc.com/hotelphotos/527/205527/2241284-lebua-at-State-Tower-Hotel-Exterior-2-DEF.jpg','Lebua at State Tower','Tailândia','10.000,00','5','2624-9889 ','http://www.lebua.com/state-tower');
INSERT INTO `hotel` (`cnpj`,`ddd`,`descricao`,`link1`,`link2`,`link3`,`nome`,`pais`,`preco`,`qtdEstrelas`,`telefone`,`linkTitle`) VALUES ('65432189','34','Concebido com a filosofia de bem viver e receber, o Dolphin se localiza no refúgio ecológico mais exclusivo do Brasil: a ilha de Fernando de Noronha.\r\nCercado por beleza estonteante, acolhido pela mata atlântica e aos pés do cartão postal mais famoso e imponente  da ilha, o Morro do Pico.  Um lugar para quem procura paz e descanso. Um refúgio acolhedor onde se encontra elegância na simplicidade e na simpatia, um lugar aconchegante e intimista  onde você se sentirá em sua própria casa de praia.','http://media-cdn.tripadvisor.com/media/photo-s/04/21/b1/2d/dolphin-hotel.jpg','http://www.brazilbookers.com/WebControl/images/wc/BR-Fernando-de-Noronha-Pousada-Dolphin-Room.jpg','http://www.turistaprofissional.com/wp-content/uploads/2013/09/lua-de-mel-em-Fernando-de-Noronha.jpg','Dolphin Hotel','Brasil','450,00','3','3453-6754','http://www.dolphinhotel.tur.br/');
